# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/desafio2?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Que Hibernate cree/actualice las tablas por ti automáticamente
spring.jpa.hibernate.ddl-auto=update

# Para ver en consola el SQL que se ejecuta por detrás
spring.jpa.show-sql=true