

# Aquí le decimos dónde guardar los datos.
#  la memoria RAM y se borra al apagar el programa.
spring.datasource.url=jdbc:h2:mem:DesafioUdb

# spring.datasource.url=jdbc:h2:file:./DesafioUdb

# Este es el traductor interno que sabe cómo comunicarse específicamente con una base de datos H2.
spring.datasource.driverClassName=org.h2.Driver

# El usuario por defecto (sa = System Administrator) y su contraseña en blanco para poder entrar.
spring.datasource.username=sa
spring.datasource.password=


# Encendemos la interfaz gráfica para poder ver nuestras tablas directamente desde el navegador web.
spring.h2.console.enabled=true

# Le decimos al sistema que la dirección para entrar a ver esa interfaz será localhost:8080/h2-console
spring.h2.console.path=/h2-console



# Le declaramos a Spring que siempre ejecute nuestros archivos "schema.sql" y "data.sql" apenas arranque el programa.
spring.sql.init.mode=always

# Aca le decimos que no puede crear tablas por si solo  porque nosotros ya construimos nuestra propia estructura exacta en el archivo schema.sql.
spring.jpa.hibernate.ddl-auto=none

# Le pedimos al sistema que sea paciente y espere a que nuestras tablas (del schema.sql) estén completamente armadas
# antes de intentar meterles datos o conectar las clases de Java.
spring.jpa.defer-datasource-initialization=true
